version: 2.1

# Default actions to perform on each Emacs version
default: &default-steps
  steps:
    - checkout
    - run: apt-get update && apt-get install -y gcc make automake autoconf libpng-dev libz-dev libpoppler-glib-dev
    - run: cask upgrade-cask || true
    - run: emacs --version
    - run: cask --version
    - run: cask install
    - run: make test

# Enumerated list of Emacs versions
jobs:
  test-emacs-26:
    docker:
      - image: silex/emacs:26-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-27:
    docker:
      - image: silex/emacs:27-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-28:
    docker:
      - image: silex/emacs:28-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master-ci-cask
        entrypoint: bash
    <<: *default-steps

workflows:
  version: 2
  ci-test-matrix:
    jobs:
      - test-emacs-26
      - test-emacs-27
      - test-emacs-28
      - test-emacs-master
